server:
  port: 80

spring:
  datasource:
    # 数据库名，从配置 database.name 中获取
    url: jdbc:mysql://localhost:3306/wangyiyun?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: toor

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER