server:
  port: 3512

spring:
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=200,expireAfterWrite=5m
  datasource:
    # 数据库名，从配置 database.name 中获取
    url: jdbc:mysql://localhost:3306/wangyiyun?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: toor
  redis:
    host: 192.168.52.128
    port: 6379
    password: '000000'
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0
    timeout: 10000