server:
  port: 8111

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quartz
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 192.168.52.128
    port: 6379
    password: '000000'
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0
    timeout: 10000
    #  Redisson配置 spring.redisson.singleServerConfig
    redisson:
      config: classpath:singleServerConfig.yaml